### ISSUE TITLE
travis is broken due to missing env variable

### ISSUE THREAD

**Issue by mvk** [mauve/vscode-terraform#154]
https://travis-ci.org/mauve/vscode-terraform/builds/489187254

```
[18:56:27] Finished 'copy-html-templates' after 5.86 ms
[18:56:27] Starting 'generate-constants-keyfile'...
[18:56:27] Starting 'create-output-directory'...
[18:56:27] Finished 'create-output-directory' after 452 μs
[18:56:27] Starting '<anonymous>'...
[18:56:27] ERROR: AppInsights Key missing in CI build
[18:56:27] '<anonymous>' errored after 4.08 ms
[18:56:27] Error: AppInsights Key missing in CI build, set APPINSIGHTS_KEY environment variable
    at gulp.task.gulp.series (/home/travis/build/mauve/vscode-terraform/gulpfile.js:151:18)
    at bound (domain.js:280:14)
    at runBound (domain.js:293:12)
    at asyncRunner (/home/travis/build/mauve/vscode-terraform/node_modules/async-done/index.js:55:18)
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickDomainCallback (internal/process/next_tick.js:128:9)
[18:56:27] 'generate-constants-keyfile' errored after 5.44 ms
[18:56:27] 'build' errored after 2.08 min
[18:56:27] 'default' errored after 2.08 min
```

**Comment by mvk** [comment]
@mauve The gulpfile.js:
https://github.com/mauve/vscode-terraform/blob/master/gulpfile.js#L143

IT assumes presence of the variable.

you should probably follow this:
https://docs.travis-ci.com/user/encryption-keys/

Good day!

**Comment by mauve** [comment]
the insights-key is currently a secret which is why PR builds fail, I have tried to detect PR builds (by checking here https://github.com/mauve/vscode-terraform/blob/master/gulpfile.js#L149) but the check seems to be wrong.

the bot-service link you posted is wrong, because this refers to my personal insights-key (which you can actually find by just opening up the plugin in your installation, so maybe I should stop bothering with the secrecy and just bundle it manually)

**Comment by mauve** [comment]
We have now switched to Azure DevOps so this should no longer be a problem (not that it had anything to do with Travis actually).

Thanks for submitting this bug and thanks for using my plugin.
